\section{Słownik pojęć}

Poniżej znajduje się krótki spis pojęć i sformułowań używanych w dalszej części dokumentu wraz z przyjętymi definicjami.

\begin{itemize}
	\item cel, zadanie -- %TODO
	\item zależności -- %TODO
	\item reguły, przepis -- %TODO
	\item jednostka koordynująca -- komputer, który koordynuje proces kompilacji i na którym został wywołany program do rozproszonej kompilacji
	\item jednostka kompilująca, jednostka pomocnicza -- komputer, który jest gotowy do uczestniczenia w procesie kompilacji, ma zainstalowane i skonfigurowane odpowiednie oprogramowanie oraz jednostka koordynująca może się z nim połączyć i zdalnie wykonywać na nim polecenia
\end{itemize}

